// <auto-generated />
using DeskCycle.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskCycle.Core.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260813174121_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DeskCycle.Core.Data.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResistanceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revolutions")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("DeskCycle.Core.Data.SessionSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revolutions")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rpm")
                        .HasColumnType("REAL");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Timestamp");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("DeskCycle.Core.Data.SessionSample", b =>
                {
                    b.HasOne("DeskCycle.Core.Data.Session", "Session")
                        .WithMany("Samples")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DeskCycle.Core.Data.Session", b =>
                {
                    b.Navigation("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
